/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.cs3560.atm_project;

/**
 *
 * @author rizen
 */
public class BalanceGUI extends javax.swing.JPanel {

    /**
     * Creates new form BalanceGUI
     */
    public BalanceGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WithdrawWindowTitle = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        balanceWindowTitle = new javax.swing.JTextField();
        balanceHeader = new javax.swing.JTextField();
        availableBalancesAmount = new javax.swing.JTextField();
        balanceBackButton = new javax.swing.JButton();
        availableBalancesTitle = new javax.swing.JLabel();

        WithdrawWindowTitle.setBackground(new java.awt.Color(0, 0, 255));
        WithdrawWindowTitle.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        WithdrawWindowTitle.setForeground(new java.awt.Color(255, 255, 255));
        WithdrawWindowTitle.setText("MyCPP Bank");
        WithdrawWindowTitle.setBorder(null);
        WithdrawWindowTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WithdrawWindowTitleActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));

        balanceWindowTitle.setBackground(new java.awt.Color(0, 0, 255));
        balanceWindowTitle.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        balanceWindowTitle.setForeground(new java.awt.Color(255, 255, 255));
        balanceWindowTitle.setText("MyCPP Bank");
        balanceWindowTitle.setBorder(null);
        balanceWindowTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceWindowTitleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(267, Short.MAX_VALUE)
                .addComponent(balanceWindowTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(236, 236, 236))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(balanceWindowTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        balanceHeader.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        balanceHeader.setForeground(new java.awt.Color(0, 0, 255));
        balanceHeader.setText("BALANCE");
        balanceHeader.setBorder(null);
        balanceHeader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceHeaderActionPerformed(evt);
            }
        });

        balanceBackButton.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        balanceBackButton.setForeground(new java.awt.Color(51, 51, 255));
        balanceBackButton.setText("BACK");
        balanceBackButton.setBorder(null);
        balanceBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceBackButtonActionPerformed(evt);
            }
        });

        availableBalancesTitle.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        availableBalancesTitle.setForeground(new java.awt.Color(51, 51, 255));
        availableBalancesTitle.setText("AVAILABLE BALANCES:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(balanceHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(248, 248, 248))
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(balanceBackButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(availableBalancesTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(availableBalancesAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(balanceHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(availableBalancesAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(availableBalancesTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(balanceBackButton)
                .addGap(51, 51, 51))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void WithdrawWindowTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WithdrawWindowTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WithdrawWindowTitleActionPerformed

    private void balanceWindowTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceWindowTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_balanceWindowTitleActionPerformed

    private void balanceHeaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceHeaderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_balanceHeaderActionPerformed

    private void balanceBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceBackButtonActionPerformed
        ATM_Project.goToScreen("home");
    }//GEN-LAST:event_balanceBackButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField WithdrawWindowTitle;
    private javax.swing.JTextField availableBalancesAmount;
    private javax.swing.JLabel availableBalancesTitle;
    private javax.swing.JButton balanceBackButton;
    private javax.swing.JTextField balanceHeader;
    private javax.swing.JTextField balanceWindowTitle;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
